### ISSUE TITLE
How to centre the react typed string?

### ISSUE THREAD

**Issue by Taimoormk** [ssbeefeater/react-typed#1]
Hey there! cheers for such an amazing repo!

I would like to know how we are supposed to centre react typed string, I am providing CSS and inline style object but no desired result.

**Comment by ssbeefeater** [comment]
you can try to use flex-box

```javascript
const styles = {
    display:'flex',
    justifyContent:'center',
}

<div style={styles}>
    <ReactTyped {...} />
</div>
```

**Comment by Taimoormk** [comment]
Awesome! cheers man.
