### ISSUE TITLE
Remove styled-components as a dependency

### ISSUE THREAD

**Issue by avin-kavish** [ssbeefeater/react-typed#10]
It doesn't make sense for us to use this library if we don't use styled-components. It's big dependency to bring in just for the sake of typing text.

**Comment by avin-kavish** [comment]
Not sure why you have done things this way, I never needed to add styles explicitly. I just did the following and it worked, I imagine the library automatically applies styles.

```
import Typed from 'typed.js'

type TypedTextProps = {
  text: string | string []
}

export default function TypedText({ text }: TypedTextProps) {
  const typeRef = useRef()

  useEffect(() => {
    let cursor: HTMLSpanElement;
    const instance = new Typed(typeRef.current, {
      typeSpeed: 80,
      backSpeed: 80,
      backDelay: 500,
      startDelay: 500,
      strings: Array.isArray(text) ? text : [ text ],
    })

    return () => instance.destroy()
  }, [ text, typeRef.current ])

  return (<span ref={typeRef}/>  )
}
```

**Comment by ssbeefeater** [comment]
The reason for the styles is the blinking animation applied on cursor. But you are right, is a big dependency for just one animation. I will consider removing it in the next version and find an alternative way.

**Comment by avin-kavish** [comment]
CSS is auto inserted by the library. Users can manuall import if needed. https://github.com/mattboldt/typed.js/blob/529dd775383da12c8c42670724443c2008d1016f/src/initializer.js#L131
