### ISSUE TITLE
Bug when you building your app for production

### ISSUE THREAD

**Issue by focux** [ssbeefeater/react-typed#2]
There's a bug when you are building your app for production. It's because you listed styled-components as peerDependency and then, if you use styled-components in your project, you are going to have version mismatch. This issue its listed in styled-component documentation: https://www.styled-components.com/docs/faqs#removing-styledcomponents-from-your-library-bundle

**Comment by SOSANA** [comment]
any updates on this? btw 1+ on this repo @ssbeefeater keep up the good work.

**Comment by ssbeefeater** [comment]
@SOSANA Thank you very much! I made a new release. Please confirm that works!
