### ISSUE TITLE
Support for react 18

### ISSUE THREAD

**Issue by HasmH** [ssbeefeater/react-typed#59]
Using `npm` version `9.5.1`
Using `node` version `v19.8.1`
Using react version `18.2.0`
Trying to install in project I am met with this error.
Workaround is: 
Downgrade react version - `npm install react@^16.3.0` or `--force` 
```
HasmH@HasmH-MacBook-Pro myproject % npm i react-typed
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hasam@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-typed@1.2.0
npm ERR! node_modules/react-typed
npm ERR!   react-typed@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/hasmh/.npm/_logs/2023-05-01T12_54_14_773Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hasmh/.npm/_logs/2023-05-01T12_54_14_773Z-debug-0.log
```

**Comment by kasir-barati** [comment]
Almost the same issue:

```cmd
$ pnpm add @reduxjs/toolkit react-redux

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 7.29.0 → 8.3.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.3.1   │
   │                Run "pnpm add -g pnpm" to update.                │
   │                                                                 │
   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

 WARN  deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
Packages: +9
+++++++++
Progress: resolved 227, reused 205, downloaded 0, added 9, done

dependencies:
+ @reduxjs/toolkit 1.9.5
+ react-redux 8.0.5

 WARN  Issues with peer dependencies found
.
└─┬ react-typed 1.2.0
  ├── ✕ unmet peer react@^16.3.0: found 18.2.0
  └── ✕ unmet peer react-dom@^16.3.0: found 18.2.0
```

Any update dear community?

**Comment by HasmH** [comment]
> Almost the same issue:
> 
> ```batchfile
> $ pnpm add @reduxjs/toolkit react-redux
> 
>    ╭─────────────────────────────────────────────────────────────────╮
>    │                                                                 │
>    │                Update available! 7.29.0 → 8.3.1.                │
>    │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.3.1   │
>    │                Run "pnpm add -g pnpm" to update.                │
>    │                                                                 │
>    │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
>    │                                                                 │
>    ╰─────────────────────────────────────────────────────────────────╯
> 
>  WARN  deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
> Packages: +9
> +++++++++
> Progress: resolved 227, reused 205, downloaded 0, added 9, done
> 
> dependencies:
> + @reduxjs/toolkit 1.9.5
> + react-redux 8.0.5
> 
>  WARN  Issues with peer dependencies found
> .
> └─┬ react-typed 1.2.0
>   ├── ✕ unmet peer react@^16.3.0: found 18.2.0
>   └── ✕ unmet peer react-dom@^16.3.0: found 18.2.0
> ```
> 
> Any update dear community?

This doesn't seem to be related to `react-typed` module, maybe try post this in `pnpm` or `react-redux` repo issue?

**Comment by kasir-barati** [comment]
@HasmH please note the last 3 line:

```cmd
 WARN  Issues with peer dependencies found
.
└─┬ react-typed 1.2.0
  ├── ✕ unmet peer react@^16.3.0: found 18.2.0
  └── ✕ unmet peer react-dom@^16.3.0: found 18.2.0
```

For some reason they installed `react-typed` and now we are here :grin:

**Comment by nemzyxt** [comment]
@kasir-barati  use the command  `npm install react-typed --force` rather than just `npm install react-typed`; the `--force` switch will forcefully reinstall it even if it's already installed (it will uninstall the existing one and reinstall it again)
The same goes for initial installation @HasmH 
You can read more [here](https://stackoverflow.com/questions/65862552/error-while-install-package-react-typed-and-others)

**Comment by antonioaltamura** [comment]
So what is the solution here? Forcing a reinstallation doesn't really solve the unmet requirement version..

**Comment by lovishGIT** [comment]
Same issue on start of 2024.
