### ISSUE TITLE
Frequent freezing on Safari

### ISSUE THREAD

**Issue by bgberk** [ssbeefeater/react-typed#9]
Typing will freeze in the middle of a string, and the cursor will continue to flash for the typing duration. When it finishes processing the string, the entire string will flash briefly, then continue with the next. In the example below, two strings display properly, and the third has the issue.
![IMG_0835](https://user-images.githubusercontent.com/16658893/58664749-236cd480-82e4-11e9-86ec-9a45cd6dda1c.GIF)

**Comment by garyanikin** [comment]
I got same problem. I have inspected the DOM, string appear there, but browser not render it.

**Comment by bgberk** [comment]
From https://github.com/mattboldt/typed.js/issues/421 I derived a fix by adding the property `contentType: ""`

**Comment by wfendler** [comment]
I encountered the same issue as @bgberk here and @bohdan-jdev0 in https://github.com/mattboldt/typed.js/issues/421.

In case it's helpful to anyone else I noticed that line breaks in template literals were causing my issue. Prettier was breaking my strings to new lines and the library must have been trying to type out those line breaks.

```jsx
// This pauses
<Typed
  strings={[
    `&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing
    elit. Dignissimos at harum modi blanditiis ipsa vitae
    iusto molestiae rerum voluptatibus?&ldquo;`,
  ]}
/>

// This works
// Change to single or double quotes to solve the new lines from the template literal
<Typed
  strings={[
    "&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos at harum modi blanditiis ipsa vitae iusto molestiae rerum voluptatibus?&ldquo;",
  ]}
/>
```
